services:
  - type: web
    name: support-chat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000 --proxy-headers
    envVars:
      - key: PORT
        value: 10000
